Prepare Firefox Add-On deploy (#5) (#6)

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -46,7 +46,24 @@ jobs:
         run: npm ci
 
       - name: Build extension for ${{ matrix.browser }}
-        run: npm run build-${{ matrix.browser }}
+        run: npm run build:${{ matrix.browser }}
+
+      - name: Validate build result
+        if: ${{ matrix.browser == 'firefox' }}
+        run: |
+          npm install -g web-ext
+
+          # lint the extension before signing
+          web-ext lint \
+            --source-dir="./dist" \
+            --output=json \
+            --pretty \
+            --warnings-as-errors
+          LINT_EXIT_CODE=$?
+          if [ $LINT_EXIT_CODE -ne 0 ]; then
+            echo "::error::Linting failed with exit code $LINT_EXIT_CODE. Build validation for Firefox failed."
+            exit 1
+          fi
 
       - name: Upload extension zip
         uses: actions/upload-artifact@v4
diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,22 +1,46 @@
 name: Deploy Browser Extension
 
 on:
+  workflow_dispatch:
+    inputs:
+        browser:
+            description: Browser platform to build for as an array (e.g., '["chrome"]", '["firefox", "chrome"]')
+            required: false
+            default: '["chrome", "firefox"]'
+            type: string
+        tag:
+            description: Tag to deploy (e.g., "ecu-test-diff-1.0.0")
+            required: true
+            type: string
   push:
     tags:
       - 'ecu-test-diff-[0-9]+.[0-9]+.[0-9]+'
-  release:
-    types: [published]
-
-concurrency:
-  group: ${{ github.workflow }}-${{ github.ref }}
-  cancel-in-progress: true
 
 jobs:
-  version-check:
+  setup:
     runs-on: ubuntu-latest
-    if: |
-      startsWith(github.ref, 'refs/tags/ecu-test-diff-') ||
-      github.event_name == 'release'
+    outputs:
+        tag-version: ${{ steps.set-tag.outputs.tag-version }}
+    steps:
+      - name: Set tag
+        id: set-tag
+        run: |
+          # determine if the workflow was triggered by a dispatch event or a tag push, and set the tag version accordingly
+            if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
+                TAG_VERSION="${{ github.event.inputs.tag }}"
+                # validate tag version
+                if [[ ! $TAG_VERSION =~ ^ecu-test-diff-[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+                    echo "❌ Invalid tag version format. Expected format: ecu-test-diff-x.y.z"
+                    exit 1
+                fi
+                echo "tag-version=$TAG_VERSION" >> $GITHUB_OUTPUT
+            else
+                TAG_VERSION="${GITHUB_REF#refs/tags/}"
+                echo "tag-version=$TAG_VERSION" >> $GITHUB_OUTPUT
+            fi
+  version-check:
+    needs: set-tag
+    runs-on: ubuntu-latest
     outputs:
       proceed: ${{ steps.version-check.outputs.proceed }}
     steps:
@@ -27,18 +51,17 @@ jobs:
           sudo apt-get update -y
           sudo apt-get install -y jq
 
-          # Tag ref of release refs/tags/<tag_name> as well
-          TAG_VERSION="${GITHUB_REF#refs/tags/ecu-test-diff-}"
+          TAG_VERSION="${{ needs.setup.outputs.tag-version }}"
           MANIFEST_VERSION=$(jq -r '.version' static/manifest.json)
           echo "Tag version: $TAG_VERSION"
           echo "Manifest version: $MANIFEST_VERSION"
-
+          
+          # extract the version from the tag
+          TAG_VERSION=${TAG_VERSION#ecu-test-diff-}
           if [ "$TAG_VERSION" != "$MANIFEST_VERSION" ]; then
             echo "❌ Tag version ($TAG_VERSION) does not match manifest version ($MANIFEST_VERSION)."
             echo "proceed=false" >> $GITHUB_OUTPUT
             exit 1
-          elif [[ "{{ github.event_name }}" == "release" ]]; then
-            ]]
           fi
 
           echo "✅ Tag version matches manifest version."
@@ -48,22 +71,46 @@ jobs:
     needs: version-check
     if: needs.version-check.outputs.proceed == 'true'
     uses: ./.github/workflows/build.yml
+    with:
+      browser: ${{ fromJSON(github.event.inputs.browser || '["chrome", "firefox"]') }}
 
   publish:
     needs: [version-check, build]
-    if: ${{ github.env.DEPLOYMENT == 'True' }}
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        browser: ['chrome'] # After supporting multiple browsers, this will be changed to ["chrome", "firefox"]
+        browser: ${{ fromJSON(github.event.inputs.browser || '["chrome", "firefox"]') }}
     steps:
       - name: Get artifact from build job
         uses: actions/download-artifact@v4
         with:
           name: ${{ matrix.browser }}-extension
-      - name: Publish to Firefox Add-on
+      - name: Set up Node v20
         if: ${{ matrix.browser == 'firefox' }}
-        run: echo "Publishing to Firefox Add-on is not implemented yet."
+        uses: actions/setup-node@v4
+        with:
+          node-version: 20
+          cache: 'npm'
+          cache-dependency-path: 'package-lock.json'
+      - name: Install web-ext
+        if: matrix.browser == 'firefox'
+        run: npm install -g web-ext
+      - name: Publish as Firefox add-on
+        if: ${{ matrix.browser == 'firefox' }}
+        env:
+          AMO_JWT_ISSUER: ${{ secrets.AMO_JWT_ISSUER }}
+          AMO_JWT_SECRET: ${{ secrets.AMO_JWT_SECRET }}
+        run: |
+          # extract artifact
+          mkdir -p "./${{ matrix.browser }}-extension"
+          unzip -o "${{ matrix.browser }}-extension.zip" -d "./${{ matrix.browser }}-extension"
+
+          # sign the extension
+          web-ext sign \
+            --api-key="$AMO_JWT_ISSUER" \
+            --api-secret="$AMO_JWT_SECRET" \
+            --channel=listed \
+            --source-dir="./${{ matrix.browser }}-extension"
       - name: Publish to Chrome Web Store
         if: ${{ matrix.browser == 'chrome' }}
         uses: mnao305/chrome-extension-upload@v5.0.0
