Enhance deployment workflow to support Firefox extension publishing and linting (#5)

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -4,12 +4,6 @@ on:
   push:
     tags:
       - 'ecu-test-diff-[0-9]+.[0-9]+.[0-9]+'
-  release:
-    types: [published]
-
-concurrency:
-  group: ${{ github.workflow }}-${{ github.ref }}
-  cancel-in-progress: true
 
 jobs:
   version-check:
@@ -55,15 +49,50 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        browser: ['chrome'] # After supporting multiple browsers, this will be changed to ["chrome", "firefox"]
+        browser: ['chrome', 'firefox']
     steps:
       - name: Get artifact from build job
         uses: actions/download-artifact@v4
         with:
           name: ${{ matrix.browser }}-extension
+      - name: Set up Node v20
+        if: ${{ matrix.browser == 'firefox' }}
+        uses: actions/setup-node@v4
+        with:
+          node-version: 20
+          cache: 'npm'
+          cache-dependency-path: 'package-lock.json'
+      - name: Install web-ext
+        if: matrix.browser == 'mozilla'
+        run: npm install -g web-ext
       - name: Publish to Firefox Add-on
         if: ${{ matrix.browser == 'firefox' }}
-        run: echo "Publishing to Firefox Add-on is not implemented yet."
+        run: |
+          # extract artifact
+          mkdir -p "./${{ matrix.browser }}-extension"
+          unzip -o "${{ matrix.browser }}-extension.zip" -d "./${{ matrix.browser }}-extension"
+
+          # lint the extension before signing
+          web-ext lint \
+            --source-dir="./${{ matrix.browser }}-extension" \
+            --output=json \
+            --pretty \
+            --warnings-as-errors
+          LINT_EXIT_CODE=$?
+          if [ $LINT_EXIT_CODE -ne 0 ]; then
+            echo "::error::Linting failed with exit code $LINT_EXIT_CODE. Submission canceled."
+            exit 1
+          fi
+
+          # sign the extension
+          web-ext sign \
+            --api-key="${{ secrets.AMO_JWT_ISSUER }}" \
+            --api-secret="${{ secrets.AMO_JWT_SECRET }}" \
+            --channel=listed \
+            --source-dir="./${{ matrix.browser }}-extension"
+        env:
+          AMO_JWT_ISSUER: ${{ secrets.AMO_JWT_ISSUER }}
+          AMO_JWT_SECRET: ${{ secrets.AMO_JWT_SECRET }}
       - name: Publish to Chrome Web Store
         if: ${{ matrix.browser == 'chrome' }}
         uses: mnao305/chrome-extension-upload@v5.0.0
